### ISSUE TITLE
Issues with Amazon Location Services via Tangram for Android. 

### ISSUE THREAD

**Issue by mohitb117** [aws-samples/amazon-location-samples#19]
Hi, 

I followed the instructions as outlined on [amazon location services tangram android demo](https://docs.aws.amazon.com/location/latest/developerguide/tutorial-tangram-es-android.html) 
 and I was having difficulty in getting the Tangram with Amazon Location Service demo setup and working correctly on my Android device. 

I tried to setup the correct identity pool information (i used the same information/configuration on [MapLibre Demo and it worked fine](https://docs.aws.amazon.com/location/latest/developerguide/tutorial-maplibre.html)

```
<resources>
    <string name="identityPoolId">us-east-1:54f2ba88-9390-498d-aaa5-0d97fb7ca3bd</string>
    <string name="mapName">TangramExampleMap</string>
    <string name="awsRegion">us-east-1</string>
    <string name="sceneUrl">https://www.nextzen.org/carto/cinnabar-style/9/cinnabar-style.zip</string>
    <string name="attribution">© 2020 HERE</string>
</resources>

```

I followed the steps in the article and i was unable to get the mapping demo to work on and was unable to see maps on devices. 

While testing i observed:
On my Pixel 2XL (Android 11) /Pixel 3 (Android 12 DP 2)  device i saw a blank screen. 
On My Samsung S10 / Pixel 4 (Android 11)  I observed: 

```
2021-04-23 13:24:06.788 27019-27019/aws.location.demo.tangram E/AndroidRuntime: FATAL EXCEPTION: main
    Process: aws.location.demo.tangram, PID: 27019
    java.lang.RuntimeException: Unable to create a native Map object! There may be insufficient memory available.
        at com.mapzen.tangram.MapController.<init>(MapController.java:163)
        at com.mapzen.tangram.MapView.getMapInstance(MapView.java:276)
        at com.mapzen.tangram.MapView.initMapController(MapView.java:173)
        at com.mapzen.tangram.MapView$1.onLibraryReady(MapView.java:120)
        at com.mapzen.tangram.MapView$1InitTask.onPostExecute(MapView.java:236)
        at com.mapzen.tangram.MapView$1InitTask.onPostExecute(MapView.java:224)
        at android.os.AsyncTask.finish(AsyncTask.java:771)
        at android.os.AsyncTask.access$900(AsyncTask.java:199)
        at android.os.AsyncTask$InternalHandler.handleMessage(AsyncTask.java:788)
        at android.os.Handler.dispatchMessage(Handler.java:106)
        at android.os.Looper.loop(Looper.java:246)
        at android.app.ActivityThread.main(ActivityThread.java:8512)
        at java.lang.reflect.Method.invoke(Native Method)
        at com.android.internal.os.RuntimeInit$MethodAndArgsCaller.run(RuntimeInit.java:602)
        at com.android.internal.os.ZygoteInit.main(ZygoteInit.java:1130)

```

And i verified that the devices had enough free RAM/heap space at the time of execution.

Is there a step that I missed in the amazon location services tangram  integration?

**Comment by mojodna** [comment]
I don't think so. It's possible that there have been upstream changes to the Tangram library that may be at play.

Does this occur in the simulator as well? Also, does using the sample Android project in this repository trigger the problem or is it only in the code you wrote based on the developer guide?

**Comment by mohitb117** [comment]
Hi @mojodna, 
I have not tried with a simulator yet (will try out a few configurations) and update this thread. 

The error that i am seeing happens with the Android project in this repository (the developer guide is identical to the sample AFAICT.

What should we do to communicate this bug if the issue persists and does this issue is repro-able by others?

Thank You!
Mohit

**Comment by mojodna** [comment]
Let me know what happens in the simulator. If you can't repro it there, we'll see if there's an upstream fix for your specific phones (there have been a few new Tangram releases since the sample doc and developer guide were written, but we haven't tried them out yet).

**Comment by mojodna** [comment]
After discussing offline, we determined that the crash was the result of using a map style that is unsupported by Tangram (`VectorEsriTopographic`). After switching to a HERE-backed source, all is golden.
