### ISSUE TITLE
Unable to use with Vite

### ISSUE THREAD

**Issue by dwightwatson** [aws-samples/amazon-location-samples#193]
I've been [following this issue about using the AWS JS SDK with Vite](https://github.com/aws/aws-sdk-js-v3/issues/2478) which may have been resolved but persists when using `amazon-location-helpers`. I'm wondering if the dependencies of this package are outdated (perhaps `@aws-amplify/core`) that are preventing this from building with Vite correctly.

Here is a [simple reproduction repo](https://github.com/dwightwatson/vite).

```
'request' is not exported by __vite-browser-external, imported by node_modules/@aws-sdk/client-cloudwatch-logs/node_modules/@aws-sdk/credential-provider-imds/dist/es/remoteProvider/httpRequest.js
file: /Users/dwight/Sites/app/node_modules/@aws-sdk/client-cloudwatch-logs/node_modules/@aws-sdk/credential-provider-imds/dist/es/remoteProvider/httpRequest.js:4:9
2: import { ProviderError } from "@aws-sdk/property-provider";
3: import { Buffer } from "buffer";
4: import { request } from "http";
            ^
5: /**
6:  * @internal
error during build:
Error: 'request' is not exported by __vite-browser-external, imported by node_modules/@aws-sdk/client-cloudwatch-logs/node_modules/@aws-sdk/credential-provider-imds/dist/es/remoteProvider/httpRequest.js
    at error (file:///Users/dwight/Sites/app/node_modules/rollup/dist/es/shared/rollup.js:1858:30)
    at Module.error (file:///Users/dwight/Sites/app/node_modules/rollup/dist/es/shared/rollup.js:12429:16)
    at Module.traceVariable (file:///Users/dwight/Sites/app/node_modules/rollup/dist/es/shared/rollup.js:12788:29)
    at ModuleScope.findVariable (file:///Users/dwight/Sites/app/node_modules/rollup/dist/es/shared/rollup.js:11440:39)
    at FunctionScope.findVariable (file:///Users/dwight/Sites/app/node_modules/rollup/dist/es/shared/rollup.js:6372:38)
    at ChildScope.findVariable (file:///Users/dwight/Sites/app/node_modules/rollup/dist/es/shared/rollup.js:6372:38)
    at FunctionScope.findVariable (file:///Users/dwight/Sites/app/node_modules/rollup/dist/es/shared/rollup.js:6372:38)
    at ChildScope.findVariable (file:///Users/dwight/Sites/app/node_modules/rollup/dist/es/shared/rollup.js:6372:38)
    at Identifier.bind (file:///Users/dwight/Sites/app/node_modules/rollup/dist/es/shared/rollup.js:7439:40)
    at CallExpression.bind (file:///Users/dwight/Sites/app/node_modules/rollup/dist/es/shared/rollup.js:5269:23)
```

**Comment by dreamorosi** [comment]
Hi @dwightwatson thank you for opening the issue.

Looking at your stack trace the error seems to be coming from `@aws-sdk/client-cloudwatch`, I need to check if it's pulled in by one of the dependencies of our package.

Regardless of that, have you tried any of the suggested workarounds from the aws sdk js issue you've linked?

**Comment by dreamorosi** [comment]
Closing the issue due to lack of activity.

If the issue persists, please feel free to reopen.
